stages:
  - scrape

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip 
  -  apt-get install -y python3-requests python3-bs4  python3-pymongo python3-dnspython

scrape:
  stage: scrape
  script:
    - python3 scrap.py
  only:
    - schedules

